"""Type stubs for delfhos.errors — SDK exceptions."""

from typing import Optional, Any

class DelfhosConfigError(Exception):
    code: str
    message_template: str
    resolution: str
    def __init__(self, message: Optional[str] = ..., **kwargs: Any) -> None: ...

class ModelConfigurationError(DelfhosConfigError): ...
class AgentConfirmationError(DelfhosConfigError): ...
class MemorySetupError(DelfhosConfigError): ...
class ToolExecutionError(DelfhosConfigError): ...
class EnvironmentKeyError(DelfhosConfigError): ...
class ToolDefinitionError(DelfhosConfigError, TypeError): ...
class OptionalDependencyError(DelfhosConfigError): ...
class ConnectionConfigurationError(DelfhosConfigError, ValueError): ...
class ConnectionFileNotFoundError(ConnectionConfigurationError, FileNotFoundError): ...
class LLMExecutionError(DelfhosConfigError): ...
class ApprovalRejectedError(DelfhosConfigError): ...

# Engine-level errors
class MemoryRetrievalError(DelfhosConfigError): ...
class CodeGenerationError(LLMExecutionError): ...
class PrefilterError(LLMExecutionError): ...
class SandboxExecutionError(ToolExecutionError): ...
class SQLSchemaError(ToolExecutionError): ...
class ConversationCompressionError(LLMExecutionError): ...

def format_error_block(code: str, message: str, hint: str, title: str = ...) -> str: ...
